---
title: "Reporte estadístico de precio USD/MXN"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r PROYECTO, echo=FALSE, message=FALSE, warning=FALSE}
# -- Borrar todos los elementos del environment
rm(list=ls())
mdir <- getwd()


#PiP por covencionalidad va a ser .0001, en el cambio dolar euro
#Se restan el precio de cierre, al precio de apertura, y lo multiplicas por el PiP.
#esta diferencia, se llama PiP.


# -- Establecer el sistema de medicion de la computadora
Sys.setlocale(category = "LC_ALL", locale = "")

# -- Huso horario
Sys.setenv(tz="America/Monterrey", TZ="America/Monterrey")
options(tz="America/Monterrey", TZ="America/Monterrey")

# -- Cargar y/o instalar en automatico paquetes a utilizar -- #

pkg <- c("base","downloader","dplyr","fBasics","forecast","grid",
         "gridExtra","httr","jsonlite","lmtest","lubridate","moments",
         "matrixStats", "PerformanceAnalytics","plyr","quantmod",
         "reshape2","RCurl","RMySQL", "stats","scales","tseries",
         "TTR","TSA","XML","xts","zoo")

inst <- pkg %in% installed.packages()
if(length(pkg[!inst]) > 0) install.packages(pkg[!inst])
instpackages <- lapply(pkg, library, character.only=TRUE)

# -- Cargar archivos desde GitHub -- #

RawGitHub <- "https://raw.githubusercontent.com/IFFranciscoME/"
ROandaAPI <- paste(RawGitHub,"ROandaAPI/master/ROandaAPI.R",sep="")
downloader::source_url(ROandaAPI,prompt=FALSE,quiet=TRUE)

# -- Parametros para usar API-OANDA

# Tipo de cuenta practice/live
OA_At <- "practice"
# ID de cuenta
OA_Ai <- 1742531
# Token para llamadas a API
OA_Ak <- "ada4a61b0d5bc0e5939365e01450b614-4121f84f01ad78942c46fc3ac777baa6" 
# Hora a la que se considera "Fin del dia"
OA_Da <- 17
# Uso horario
OA_Ta <- "America/Mexico_City"
# Instrumento
OA_In <- "USD_MXN"
# Granularidad o periodicidad de los precios H4 = Cada 4 horas
# S5, S10, S30, M1, 
OA_Pr <- "D" #esto es lo unico que le puedes cambiarle
# Multiplicador de precios para convertir a PIPS
MultPip_MT1 <- 10000

Precios_Oanda <- HisPrices(AccountType = OA_At, Granularity = OA_Pr,
                           DayAlign = OA_Da, TimeAlign = OA_Ta, Token = OA_Ak,
                           Instrument = OA_In, 
                           Start = "2016-11-06", End = "2018-11-06", Count = NULL)

library(quantmod)

Close <- xts(x = Precios_Oanda$Close, order.by = Precios_Oanda$TimeStamp)

plot.xts(Close)

hist(dailyReturn(Close))



#ESTADISTICOS

###Bollinger Bands
## The examples below show the differences between using a
## High-Low-Close series, and just a close series when
## calculating Bollinger Bands.
bbands.HLC <- BBands( Precios_Oanda[,c("High","Low","Close")] )
bbands.close <- BBands( Precios_Oanda[,"Close"] )


###SMA
sma.20 <- SMA(Precios_Oanda[,"Close"], 20)
plot.ts(sma.20)


###EMA
ema.20 <- EMA(Precios_Oanda[,"Close"], 20)
plot.ts(ema.20)

###ALMA
dema <- DEMA(Precios_Oanda[,"Close"])
plot.ts(dema)

###WMA
wma <- WMA(Precios_Oanda[,"Close"], 20)
plot.ts(wma)

###RSI
price <- Precios_Oanda[,"Close"]
rsi <- RSI(price)


###Stochastic Oscillator
stochOSC <- stoch(Precios_Oanda[,c("High","Low","Close")])
stochWPR <- WPR(Precios_Oanda[,c("High","Low","Close")])
plot(tail(stochOSC[,"fastK"], 100), type="l",
     main="Fast %K and Williams %R", ylab="",
     ylim=range(cbind(stochOSC, stochWPR), na.rm=TRUE) )
lines(tail(stochWPR, 100), col="blue")
lines(tail(1-stochWPR, 100), col="red", lty="dashed")
stoch2MA <- stoch( Precios_Oanda[,c("High","Low","Close")],
                   maType=list(list(SMA), list(EMA, wilder=TRUE), list(SMA)) )
SMI3MA <- SMI(Precios_Oanda[,c("High","Low","Close")],
              maType=list(list(SMA), list(EMA, wilder=TRUE), list(SMA)) )
stochRSI <- stoch( RSI(Precios_Oanda[,"Close"]) )


###MACD
macd <- MACD( Precios_Oanda[,"Close"], 12, 26, 9, maType="EMA" )
plot.ts(macd)

##GRAFICA BOLLINGER BANDS Y RSI
chartSeries(
  Close,
  theme = chartTheme("white"),
  TA = c(addBBands(),addTA(RSI(Close)))
)


######### SMA
library(tidyquant)

Candle <- ggplot(data=`Precios_Oanda`, aes(x=TimeStamp, y=Close)) +
  geom_candlestick(aes(open=Open, high=High, low=Low, close=Close), na.rm = TRUE,
                   color_up = "darkgreen", color_down = "darkred",  fill_up  = "darkgreen", fill_down  = "darkred")+
  geom_ma(ma_fun = SMA, n = 21, linetype = 5, size = 1.25) +
  labs(title = "USD/MXN, 21 day simple moving average",y="Closing Price", x="Date") +
  theme_tq()
Candle

Bar <- ggplot(data=`Precios_Oanda`, aes(x=TimeStamp, y=Close)) +
  geom_barchart(aes(open=Open, high=High, low=Low, close=Close), na.rm = TRUE,
                color_up = "darkblue", color_down = "darkred", size = 1)  
labs(title = "USD/MXN",y="Closing Price", x="TimeStamp") + 
  theme_tq()
Bar
#####sm

######### EMA
library(tidyquant)

Candle <- ggplot(data=`Precios_Oanda`, aes(x=TimeStamp, y=Close)) +
  geom_candlestick(aes(open=Open, high=High, low=Low, close=Close), na.rm = TRUE,
                   color_up = "darkgreen", color_down = "darkred",  fill_up  = "darkgreen", fill_down  = "darkred")+
  geom_ma(ma_fun = EMA, n = 21, linetype = 5, size = 1.25) +
  labs(title = "USD/MXN, 21 day exponential moving average",y="Closing Price", x="Date") +
  theme_tq()
Candle

######### WMA
library(tidyquant)

Candle <- ggplot(data=`Precios_Oanda`, aes(x=TimeStamp, y=Close)) +
  geom_candlestick(aes(open=Open, high=High, low=Low, close=Close), na.rm = TRUE,
                   color_up = "darkgreen", color_down = "darkred",  fill_up  = "darkgreen", fill_down  = "darkred")+
  geom_ma(ma_fun = WMA, n = 21, linetype = 5, size = 1.25) +
  labs(title = "USD/MXN, 21 day weighted moving average",y="Closing Price", x="Date") +
  theme_tq()
Candle

######### DEMA
library(tidyquant)

Candle <- ggplot(data=`Precios_Oanda`, aes(x=TimeStamp, y=Close)) +
  geom_candlestick(aes(open=Open, high=High, low=Low, close=Close), na.rm = TRUE,
                   color_up = "darkgreen", color_down = "darkred",  fill_up  = "darkgreen", fill_down  = "darkred")+
  geom_ma(ma_fun = DEMA, n = 21, linetype = 5, size = 1.25) +
  labs(title = "USD/MXN, 21 day double exponential moving average",y="Closing Price", x="Date") +
  theme_tq()
Candle


```

